title: Ochre
description: Music by Christopher Leary.
author: Chris
url: https://ochremusic.com
baseurl: ''
logo: /assets/logo.png

excerpt_separator: <!--more-->
permalink: "/:year/:month/:day/:title"
paginate_path: /page/:num/
paginate: 10

twitter:
  username: ochremusic
facebook:
  app_id: 341352649553991
  publisher: 190149549210
  admins: 100000537844760

social:
  name: Ochre
  links:
    - https://twitter.com/ochremusic
    - https://www.facebook.com/ochremusic
    - https://soundcloud.com/ochre
    - https://ochre.bandcamp.com/
    - https://bandcamp.ochremusic.com/
    - https://www.youtube.com/user/ochremusic

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      image: /assets/logo.png
  - scope:
      path: ''
      type: posts
    values:
      category: [Ochre]
      image-alt: ''
      layout: post
      published: false

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jemoji
  - jekyll_picture_tag

source: src
destination: public

include: ['_pages', 'assets']

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - webpack/
  - '*.sh'
  - '*.rdb'
  - .DS_Store

picture:
  source: 'assets'
  output: 'assets/opt'
