backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Published', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Categories', name: 'categories', widget: 'list', default: ['Ochre'] }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Featured Image', name: 'image', widget: 'image', required: false }
      - {
          label: 'Image alt. text',
          name: 'image-alt',
          widget: 'string',
          default: '',
          required: false,
        }
      - {
          label: 'Image focus',
          name: 'image-class',
          widget: 'select',
          options: [{ label: 'Top', value: 'top' }, { label: 'Bottom', value: 'bottom' }],
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
